language: php

php:
  - 5.5
  - 5.6
#  there is no stable tag of jms/job-queue-bundle that supports 7.0 now. TODO enable when it appeares
#  - 7.0

before_install:
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

before_script:
  - composer self-update
  - composer global --no-suggest require hirak/prestissimo
  - composer require satooshi/php-coveralls -n

install:
  - composer install --no-suggest --prefer-dist

script:
 - mkdir -p build/logs
 - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
 - php vendor/bin/coveralls -v

git:
  depth: 5
