language: php

php:
  - 5.5
  - 5.6
  - hhvm
#  there is no stable tag of jms/job-queue-bundle that supports 7.0 now. TODO enable when it appeares
#  - 7.0

before_script:
  - composer self-update
  - composer require satooshi/php-coveralls -n

script:
 - mkdir -p build/logs
 - phpunit --coverage-clover build/logs/clover.xml

after_script:
 - php vendor/bin/coveralls -v

git:
  depth: 5