#!/usr/bin/env php
<?php
declare(strict_types=1);

use Gtt\Bundle\WorkflowExtensionsBundle\Functional\ScheduleCaseTest;
use Symfony\Component\Console\Input\ArgvInput;

set_time_limit(0);

/**
 * @var Composer\Autoload\ClassLoader $loader
 */
$loader = require __DIR__ . '/../../../bootstrap.php';

$case = new ScheduleCaseTest();
$application = $case->initApplication();
$application->run(new ArgvInput());
